= Ethernet pin definition

Pin definitions when viewed facing the connector on cable key on the right side.

[cols="1,^3,^3,^3,^3,^3,^3,^3,^3,>.^2",grid=rows]
|===
| | C1 | C2 | C3 | C4 | C5 | C6 | C7 | C8 |

| H

G | DP4-

DP4+ | DP8- 

DP8+ | DP12-

DP12+ | DP16-

DP16+ | DP20-

DP20+ | DP24-

DP24+ | DP28-

DP28+ | DP32-

DP32+ .4+| KEY

| F

E | DP3-

DP3+ | DP7- 

DP7+ | DP11-

DP11+ | DP15-

DP15+ | DP19-

DP19+ | DP23-

DP23+ | DP27-

DP27+ | DP31-

DP31+ 

| D

C | DP2-

DP2+ | DP6- 

DP6+ | DP10-

DP10+ | DP14-

DP14+ | DP18-

DP18+ | DP23-

DP23+ | DP26-

DP26+ | DP30-

DP30+ 

| B

A | DP1-

DP1+ | DP5- 

DP5+ | DP9-

DP9+ | DP13-

DP13+ | DP17-

DP17+ | DP22-

DP22+ | DP25-

DP25+ | DP29-

DP29+ 

10+| GROUND SHIELD TO GROUND

|===

== Ethernet signal definition

[cols="1,^3,^3,^3,^3,^3,^3,^3,^3,>.^2",grid=rows]

|===
|  | C1 | C2 | C3 | C4 | C5 | C6 | C7 | C8 |  

| H

G | BI_DD-

BI_DD+ | NC 

NC | SFP2_LN1_RX_N

SFP2_LN1_RX_P | SFP4_LN1_RX_N

SFP4_LN1_RX_P | QSFP1_LN2_RX_N

QSFP1_LN2_RX_p | QSFP1_LN1_RX_N

QSFP1_LN1_RX_P | QSFP2_LN2_RX_N

QSFP2_LN2_RX_P | QSFP2_LN1_RX_N

QSFP2_LN1_RX_P .4+| KEY 

| F

E | BI_DC-

BI_DC+ | NC 

NC | SFP1_LN1_RX_N

SFP1_LN1_RX_P | SFP3_LN1_RX_N

SFP3_LN1_RX_P | QSFP1_LN4_RX_N

QSFP1_LN4_RX_P | QSFP1_LN3_RX_N

QSFP1_LN3_RX_P | QSFP2_LN4_RX_N

QSFP2_LN4_RX_P | QSFP2_LN3_RX_N

QSFP2_LN3_RX_P 

| D

C | BI_DB-

BI_DB+ | NC 

NC | SFP2_LN1_TX_N

SFP2_LN1_TX_P | SFP4_LN1_TX_N

SFP4_LN1_TX_P | QSFP1_LN3_TX_N

QSFP1_LN3_TX_P | QSFP1_LN4_TX_N

QSFP1_LN4_TX_P | QSFP2_LN3_TX_N

QSFP2_LN3_TX_P | QSFP2_LN4_TX_N

QSFP2_LN4_TX_P 

| B

A | BI_DA-

BI_DA+ | NC 

NC | SFP1_LN1_TX_N

SFP1_LN1_TX_P | SFP3_LN1_TX_N

SFP3_LN1_TX_P | QSFP1_LN1_TX_N

QSFP1_LN1_TX_P | QSFP1_LN2_TX_N

QSFP1_LN2_TX_P | QSFP2_LN1_TX_N

QSFP2_LN1_TX_P | QSFP2_LN2_TX_N

QSFP2_LN2_TX_P

10+| GROUND SHIELD TO GROUND

|===


